Public Class 字体控制

    Public Shared Sub 更新所有控件字体属性()
        SetControlFont(设置_v6.实例对象.字体, FormMain_v6, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_起始页面, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_准备文件, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_编码队列, , True)
        Form_v6_编码队列.任务菜单.MenuFont = New Font(设置_v6.实例对象.字体, Form_v6_编码队列.任务菜单.MenuFont.Size, Form_v6_编码队列.任务菜单.MenuFont.Style)
        Form_v6_编码队列.任务菜单.DescriptionFont = New Font(设置_v6.实例对象.字体, Form_v6_编码队列.任务菜单.MenuFont.Size, Form_v6_编码队列.任务菜单.MenuFont.Style)
        Form_v6_编码队列.右键菜单.MenuFont = New Font(设置_v6.实例对象.字体, Form_v6_编码队列.右键菜单.MenuFont.Size, Form_v6_编码队列.右键菜单.MenuFont.Style)
        Form_v6_编码队列.右键菜单.DescriptionFont = New Font(设置_v6.实例对象.字体, Form_v6_编码队列.右键菜单.MenuFont.Size, Form_v6_编码队列.右键菜单.MenuFont.Style)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_参数总览, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_预设管理, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_输出文件设置, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_解码参数, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_视频编码器, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_画面帧, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_质量, , True)
        Form_v6_参数面板.私有界面_质量.预制条目菜单.MenuFont = New Font(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_质量.预制条目菜单.MenuFont.Size, Form_v6_参数面板.私有界面_质量.预制条目菜单.MenuFont.Style)
        Form_v6_参数面板.私有界面_质量.预制条目菜单.DescriptionFont = New Font(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_质量.预制条目菜单.DescriptionFont.Size, Form_v6_参数面板.私有界面_质量.预制条目菜单.DescriptionFont.Style)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_色彩管理, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_视频帧服务器, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_音频参数, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_剪辑区间, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_滤镜排序, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_自定义参数, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_自定义参数说明, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_流自定义参数, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_在位置插入参数, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_完全自己写模式, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_流控制, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_附加内容, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_元数据, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_章节, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_参数面板.私有界面_附件, , True)

        SetControlFont(设置_v6.实例对象.字体, Form_v6_Agent, , True)

        SetControlFont(设置_v6.实例对象.字体, Form_v6_社区_个人中心, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_社区_浏览内容, , True)

        SetControlFont(设置_v6.实例对象.字体, Form_v6_媒体信息, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_调试播放器, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_性能监控, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_集成工具, , True)

        SetControlFont(设置_v6.实例对象.字体, Form_v6_集成工具_合并, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_集成工具_混流, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_集成工具_抽流, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_集成工具_质量评测, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_集成工具_Whisper生成字幕, , True)

        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_LakeUI性能选项, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_LakeUI视觉体验, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_LakeUIHDR, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_LakeUI许可证, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_界面显示, {Form_v6_设置_界面显示.MCB_全局字体}, True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_功能设定, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_性能调度, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_更新选项, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_转译辅助, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_远程调用, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_Agent, , True)
        SetControlFont(设置_v6.实例对象.字体, Form_v6_设置_个性化, , True)

        SetControlFont(设置_v6.实例对象.字体, Form_v6_支持者, , True)

    End Sub


End Class
