<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <StartupObject>FFmpegFreeUI.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <UseWPF>True</UseWPF>
    <!--<PublishReadyToRun>True</PublishReadyToRun>
    <PublishReadyToRunEmitSymbols>True</PublishReadyToRunEmitSymbols>-->
    <SelfContained>False</SelfContained>
    <!--<IncludeNativeLibrariesForSelfExtract>True</IncludeNativeLibrariesForSelfExtract>-->
    <!--<EnableCompressionInSingleFile>True</EnableCompressionInSingleFile>-->
    <Authors>1059 Studio</Authors>
	<Company>1059 Studio</Company>
	<AssemblyVersion>6.2.15</AssemblyVersion>
	<FileVersion>6.2.15</FileVersion>
	<Version>6.2.15</Version>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ApplicationIcon>ico.ico</ApplicationIcon>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <Title>FFmpegFreeUI</Title>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Language\**" />
    <EmbeddedResource Remove="Language\**" />
    <None Remove="Language\**" />
    <Page Remove="Language\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ico.ico" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
	<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.13.0" />
	<PackageReference Include="System.Management" Version="10.0.9" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LakeUI">
      <HintPath>..\..\LakeUI\LakeUI\bin\Debug\net10.0-windows10.0.17763.0\LakeUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource1.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource1.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="AviSynth.avs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
